from .student import student_assignments_resources as student_assignments_resources
from .teacher import teacher_assignments_resources as teacher_assignments_resources
from .principal import principal_assignments_resources as principal_assignments_resources
