"""Initial migration.

Revision ID: 6e45b1cba334
Revises: 52a401750a76
Create Date: 2024-05-24 08:54:19.877574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e45b1cba334'
down_revision = '52a401750a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###
